<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MusiQL.Core\MusiQL.Core.csproj" />
    <ProjectReference Include="..\..\src\MusiQL.Data\MusiQL.Data.csproj" />
    <ProjectReference Include="..\..\src\MusiQL.Api\MusiQL.Api.csproj" />
    <ProjectReference Include="..\..\src\MusiQL.Etl\MusiQL.Etl.csproj" />
  </ItemGroup>

</Project>
