<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MusiQL.Etl</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="SharpZipLib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MusiQL.Core\MusiQL.Core.csproj" />
    <ProjectReference Include="..\MusiQL.Data\MusiQL.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sql\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sample\mbdump\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
