// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusiQL.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusiQL.Data.Migrations
{
    [DbContext(typeof(MusiQLDbContext))]
    [Migration("20260925152349_CoveringVoteIndexes")]
    partial class CoveringVoteIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusiQL.Data.App.UserLibrary", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("RecordingId")
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RecordingId");

                    b.HasIndex("RecordingId");

                    b.ToTable("user_library", "app");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.Artist", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<short?>("BeginYear")
                        .HasColumnType("smallint")
                        .HasColumnName("begin_year");

                    b.Property<short?>("EndYear")
                        .HasColumnType("smallint")
                        .HasColumnName("end_year");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sort_name");

                    b.HasKey("Id");

                    b.HasIndex("BeginYear");

                    b.HasIndex("Mbid")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("artist", "catalog");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.ArtistGenre", b =>
                {
                    b.Property<long>("ArtistId")
                        .HasColumnType("bigint")
                        .HasColumnName("artist_id");

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint")
                        .HasColumnName("genre_id");

                    b.Property<int>("Votes")
                        .HasColumnType("integer")
                        .HasColumnName("votes");

                    b.HasKey("ArtistId", "GenreId");

                    b.HasIndex("GenreId", "ArtistId");

                    b.ToTable("artist_genre", "catalog");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.Genre", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Mbid")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("genre", "catalog");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.Recording", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ArtistId")
                        .HasColumnType("bigint")
                        .HasColumnName("artist_id");

                    b.Property<short?>("FirstReleaseYear")
                        .HasColumnType("smallint")
                        .HasColumnName("first_release_year");

                    b.Property<int?>("LengthMs")
                        .HasColumnType("integer")
                        .HasColumnName("length_ms");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ReleaseGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("release_group_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("FirstReleaseYear");

                    b.HasIndex("Mbid")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("ReleaseGroupId");

                    b.ToTable("recording", "catalog");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.RecordingGenre", b =>
                {
                    b.Property<long>("RecordingId")
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint")
                        .HasColumnName("genre_id");

                    b.Property<int>("Votes")
                        .HasColumnType("integer")
                        .HasColumnName("votes");

                    b.HasKey("RecordingId", "GenreId");

                    b.HasIndex("GenreId", "RecordingId");

                    b.ToTable("recording_genre", "catalog");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.Release", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ArtistId")
                        .HasColumnType("bigint")
                        .HasColumnName("artist_id");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ReleaseGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("release_group_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Mbid")
                        .IsUnique();

                    b.HasIndex("ReleaseGroupId");

                    b.ToTable("release", "catalog");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.ReleaseGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ArtistId")
                        .HasColumnType("bigint")
                        .HasColumnName("artist_id");

                    b.Property<short?>("FirstReleaseYear")
                        .HasColumnType("smallint")
                        .HasColumnName("first_release_year");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryType")
                        .HasColumnType("text")
                        .HasColumnName("primary_type");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("FirstReleaseYear");

                    b.HasIndex("Mbid")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("release_group", "catalog");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.ReleaseGroupGenre", b =>
                {
                    b.Property<long>("ReleaseGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("release_group_id");

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint")
                        .HasColumnName("genre_id");

                    b.Property<int>("Votes")
                        .HasColumnType("integer")
                        .HasColumnName("votes");

                    b.HasKey("ReleaseGroupId", "GenreId");

                    b.HasIndex("GenreId", "ReleaseGroupId");

                    b.ToTable("release_group_genre", "catalog");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.ArtistGenre", b =>
                {
                    b.HasOne("MusiQL.Data.Catalog.Artist", "Artist")
                        .WithMany("Genres")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusiQL.Data.Catalog.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.Recording", b =>
                {
                    b.HasOne("MusiQL.Data.Catalog.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusiQL.Data.Catalog.ReleaseGroup", "ReleaseGroup")
                        .WithMany()
                        .HasForeignKey("ReleaseGroupId");

                    b.Navigation("Artist");

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.RecordingGenre", b =>
                {
                    b.HasOne("MusiQL.Data.Catalog.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusiQL.Data.Catalog.Recording", "Recording")
                        .WithMany("Genres")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.Release", b =>
                {
                    b.HasOne("MusiQL.Data.Catalog.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusiQL.Data.Catalog.ReleaseGroup", "ReleaseGroup")
                        .WithMany()
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.ReleaseGroup", b =>
                {
                    b.HasOne("MusiQL.Data.Catalog.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.ReleaseGroupGenre", b =>
                {
                    b.HasOne("MusiQL.Data.Catalog.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusiQL.Data.Catalog.ReleaseGroup", "ReleaseGroup")
                        .WithMany("Genres")
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.Artist", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.Recording", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("MusiQL.Data.Catalog.ReleaseGroup", b =>
                {
                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
